name: Build Artifacts
on:
  workflow_call:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        type: string
      release_version:
        description: 'Release version number (e.g. v0.3.7-alpha)'
        required: true
        type: string
      info_version:
        description: 'Informational version number (e.g. 0.3.7-alpha)'
        required: true
        type: string
    secrets:
      gh_token:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      NEXUS_REPO:
        required: true
      NUGET_API_KEY:
        required: true

jobs:
  build_and_upload:
    name: Build & Upload
    runs-on: self-hosted
    container:
      image: registry.crookedcactus.net/v2/dev-tools/dotnet:1.0.2
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Clean
        run: dotnet clean --configuration Release && dotnet nuget locals all --clear

      - name: Install dependencies
        run: dotnet restore

      - name: Pack
        shell: bash
        run: |
          release_name="AuthLib-${{ inputs.release_version }}"
          echo "RELEASE_NAME=${release_name}.nupkg" >> $GITHUB_ENV

          dotnet pack -c Release -o "$release_name"

      - name: Publish to Nexus
        run: |
          dotnet nuget push ./${{ env.RELEASE_NAME }} --source ${{ secrets.NEXUS_REPO }} --api-key ${{ secrets.NUGET_API_KEY }} 
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ inputs.release_tag }}
          files: |
            ${{ env.RELEASE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
